### ISSUE TITLE
ImageButtons don't respond to clicks

### ISSUE THREAD

**Issue by Hi-ImKyle** [mellinoe/ImGui.NET#92] opened 2018-12-23 16:13 UTC
#51 says `PushID` and `PopID` fixes this issue but it doesn't at all. 

If the button has a image assigned to it, it only returns false. 

![image](https://user-images.githubusercontent.com/25551312/50385439-6c818280-06cd-11e9-9706-a5d327a4aa91.png)
`cl` in this image is not being incremented at all. Where as if the button has no image assigned to it, `IntPtr.Zero`, the button works just fine and `cl` is incremented.

How do I get the image button to act normal with a image assigned to it.

**Comment by Hi-ImKyle** [comment] 2018-12-23 22:36
`ImGui.IsItemActive()` does help as a replacement to check if it was pressed, just wondering if there's any reason why it wouldn't be working normally?

**Comment by mellinoe** [comment] 2018-12-24 00:37
I’m pretty busy this week, so I’m not able to test this right away. PushID / PopID should be working. The fact that your variable is never being incremented implies that it’s never returning true, which doesn’t necessarily have anything to do with the button’s ID. Are regular buttons, etc. working correctly?

**Comment by mellinoe** [comment] 2018-12-24 05:19
Hey @Hi-ImKyle I just tried this with a quick modification to the sample program here, and it worked as expected. If I didn't push a unique ID to both, then only the first button was responding to clicks. With a unique ID, both images were responding appropriately to clicks in their respective regions. Seems to work fine with 3 images (and 3 unique IDs) as well. Are you able to confirm whether other buttons / clicks are working correctly? Does it work if you have a single ImageButton?

**Comment by Hi-ImKyle** [comment] 2018-12-25 00:35
all the image buttons dont work and they all have different images, they all work fine if their IntPtr you pass is 0. Regular buttons are just fine.

**Comment by mellinoe** [comment] 2018-12-25 05:06
Can you provide a more complete project that reproduces the issue? From my testing, the behavior is very different and any issues are resolved by using Push/PopID.

**Closed** 2019-01-14 21:48 UTC

**Comment by kotokun2** [comment] 2019-05-22 19:46
I had the same problem.
The reason that this was happening (for me) was because i was giving the button ids in a function that was called on NewFrame() so it was incrementing the IDs all the time.
I just moved the id assignments before  <b>while (!glfwWindowShouldClose(window)) <b> and it worked perfectly.
Hope this helps any one that is new to all of this like me :)
