### ISSUE TITLE
ImGui.Text(null) causes it to display previous text and ???? 

### ISSUE THREAD

**Issue by se5a** [mellinoe/ImGui.NET#128] opened 2019-07-11 02:14 UTC
![image](https://user-images.githubusercontent.com/1490538/61016782-f92f2c00-a3e4-11e9-8e5f-8be836c7aa60.png)

While this may not be something that you'd do in practice, the problem rares its ugly head if you have an object ie:
```
struct DataObject()
{
    string Name;
    string SomeData;
}
```
then only populate the name, and try print it:
```
List<DataObject> listOfData;
listOfData[0] = new DataObject(){Name = "Thing", SomeData = ThingValue};
listOfData[1] = new DataObject(){Name = "AlsoThing"};

foreach(var item in listOfData)
{
ImGui.Text(item.Name);
ImGui.SameLine();
ImGui.Text(item.SomeData);
}
```

in my particular use case, AlsoThing had the same data value as Thing, so I did't bother populating it, just leaving it null, previous versions (somewhere 1.6?) this just printed nothing.

**Comment by mellinoe** [comment] 2019-07-11 02:49
This is a duplicate of https://github.com/mellinoe/ImGui.NET/issues/120. As I mentioned there, fixing the `null` parameter marshalling shouldn't be too hard, but I need to find some time to implement and test it.

**Closed by mellinoe** 2019-07-11 02:49 UTC
